package cli.utils

protected const CARRIAGE_RETURN = r'\r'
protected const ENTER = r'\n'
protected const DELETE = r'\u{7F}'
protected const BACK = r'\b'
protected const TAB = r'\t'
protected const ARROW_UP = r'\u{2191}'
protected const ARROW_DOWN = r'\u{2193}'
protected const ARROW_LEFT = r'\u{2190}'
protected const ARROW_RIGHT = r'\u{2192}'
protected let CONTROL_RUNES = [CARRIAGE_RETURN, ENTER, DELETE, BACK, TAB, ARROW_UP, ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT]
